apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
      version: 1.0.0
      tier: front
  template:
    metadata:
      labels:
        app: nginx
        version: 1.0.0
        tier: front
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: nginx-port
          protocol: TCP
