apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - name: nginx-port
      containerPort: 80
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  labels:
    app: nginx
    environment: dev
spec:
  type: NodePort
  selector:
    app: nginx
    environment: dev
  ports:
  - name: nginx-lb
    targetPort: nginx-port
    nodePort: 30007
    port: 80


    
  