apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    app: nginx
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - name: nginx-lb
      protocol: TCP
      containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
    environemnt: dev
  ports: 
  - name: service-lb
    port: 80
    targetPort: nginx-lb

      

