apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-configmap-vol
data:
   game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
   user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap-env
spec:
  containers:
    - name: cricketplayers
      image: alpine
      command: ["sleep", "3600"]
      volumeMounts:
      - name: pod-configmap-vol 
        mountPath: "/config"
        readOnly: true

  volumes:
  - name: pod-configmap-vol
    configMap:
      name: pod-configmap-vol
      items:
      - key: "game.properties"
        path: "game.properties"
      - key: "user-interface.properties"
        path: "user-interface.properties"

